---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 2c9f875913ee60ca25ce70243dc24d5b6415598c # frozen: v4.6.0
    hooks:
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: f12edd9c7be1c20cfa42420fd0e6df71e42b51ea # frozen: v4.0.0-alpha.8
    hooks:
      - id: prettier
        stages: [commit]

  - repo: https://github.com/jorisroovers/gitlint
    rev: acc9d9de6369b76d22cb4167029d2035e8730b98 # frozen: v0.19.1
    hooks:
      - id: gitlint

  - repo: https://github.com/chriskuehl/puppet-pre-commit-hooks.git
    rev: 8106e1ded84fc9a9e67a676e435d794c039e5d69 # frozen: v2.2.0
    hooks:
      - id: epp-validate
      - id: erb-validate
      - id: puppet-lint
        args:
          - --with-context
          - --no-autoloader_layout-check
      - id: puppet-validate
      - id: ruby-validate

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 38980559e3a605691d6579f96222c30778e5a69e # frozen: 3.0.0
    hooks:
      - id: shellcheck
